import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect, Fragment } from "react";
import axios from "axios";
import { useState } from "react";

export default function Home() {
  const [ans, setAns] = useState("");
  const [questions, setQuestions] = useState(["ab", "cd", "ef"]);
  const [answers, setAnswers] = useState(["01", "23", "45"]);
  const [inputData, setInputData] = useState("");
  const [uri, setURI] = useState("");
  // const [inputQuestion, setInputQuestion] = useState('');

  const handleClick = async () => {
    try {
      const response = await axios.get("http://127.0.0.1:3000/api/health");
      console.log(response.data);
      setAns(response.data.message);
    } catch (error) {
      console.error(error);
    }
  };

  //input data button
  const handleSubmit = async (e) => {
    e.preventDefault();
    const data = {
      question: inputData,
      model: "gpt-3.5-turbo",
      temperature: 0,
      url: uri,
    };
    setQuestions((prevQuestions) => [...prevQuestions, inputData]);

    try {
      const response = await axios.post("http://127.0.0.1:3000/api/live", data);
      console.log(response.data);
      // setAnswer(response.data.response);
      setAnswers((prevResponses) => [...prevResponses, response.data.response]);
      setInputData("");
    } catch (error) {
      console.error(error);
    }
  };

  const submitQuestion = async (e) => {
    e.preventDefault();
    const data = {
      question: inputData,
    };
    setQuestions((prevQuestions) => [...prevQuestions, inputData]);

    try {
      const response = await axios.post("http://127.0.0.1:3000/api/question", data);
      console.log(response.data);
      // setAnswer(response.data.response);
      setAnswers((prevResponses) => [...prevResponses, response.data.response]);
      setInputData("");
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>new ai app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.box2}>
        <div className={styles.response}>
          <div className={styles.convo_body}>

            <div className={styles.main_container}>
            <div className={styles.header}>
              <p>Ask me anything!</p>
            </div>
              {questions.map((question, index) => (
                <Fragment key={index}>
                  <div className={styles.questions_container}>
                    <div className={styles.questions_body}>
                      <Image
                        className={styles.icon}
                        src="/usericon.webp"
                        width={32}
                        height={32}
                        alt="user"
                      />
                      <p className={styles.response_text}>{question}</p>
                    </div>
                  </div>

                  <div className={styles.response_container}>
                    {answers.length > index && (
                      <div className={styles.questions_body}>
                        <Image
                          className={styles.icon}
                          src="/usericon.webp"
                          width={32}
                          height={32}
                          alt="user"
                        />
                        <p className={styles.response_text}>{answers[index]}</p>
                      </div>
                    )}
                  </div>
                </Fragment>
              ))}
            </div>

            {/* </div> */}
          </div>
        </div>

        <div className={styles.form}>
          <form className={styles.mainform} onSubmit={submitQuestion}>
            <textarea
              className={styles.textarea}
              rows="1"
              maxLength="512"
              id="userInput"
              name="userInput"
              placeholder="Type your question..."
              // className="Home_textarea__lSHf7"
              value={inputData}
              onChange={(e) => setInputData(e.target.value)}
            ></textarea>
            {/* <textarea
              className={styles.textarea}
              rows="1"
              maxlength="512"
              id="userInput"
              name="userInput"
              value={uri}
              placeholder="url"
              onChange={(e) => setURI(e.target.value)}
            ></textarea> */}
            <br />
            <button type="submit" className={styles.textarea}>
              Go!
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
